"""stakeholder_notebooks — Generate presentation-ready notebooks for non-technical audiences."""

from dataclasses import dataclass, field
from pathlib import Path
import nbformat
from nbformat.v4 import new_notebook, new_markdown_cell, new_code_cell


@dataclass
class StakeholderSpec:
    title: str
    executive_summary: str
    hypothesis_id: str
    data_source: str
    key_findings: list[str]
    figure_paths: list[str] = field(default_factory=list)
    metrics: dict | None = None


def _hidden_code_cell(code: str) -> nbformat.NotebookNode:
    """Create a code cell with hide-input tag."""
    cell = new_code_cell(code)
    cell.metadata["tags"] = ["hide-input"]
    return cell


def generate_stakeholder_notebook(spec: StakeholderSpec) -> nbformat.NotebookNode:
    """Narrative-heavy notebook for non-technical readers."""
    nb = new_notebook()
    cells = []

    # Title + executive summary
    cells.append(new_markdown_cell(
        f"# {spec.title}\n\n"
        f"**Summary:** {spec.executive_summary}\n\n"
        f"*Analysis ID: {spec.hypothesis_id}*"
    ))

    # Hidden imports
    cells.append(_hidden_code_cell(
        "import pandas as pd\nimport matplotlib.pyplot as plt\n"
        "import seaborn as sns\nsns.set_palette('colorblind')\n"
        "%matplotlib inline"
    ))

    # Key findings
    findings_md = "## Key Findings\n\n"
    for i, f in enumerate(spec.key_findings, 1):
        findings_md += f"**{i}.** {f}\n\n"
    cells.append(new_markdown_cell(findings_md))

    # Metrics (plain language)
    if spec.metrics:
        metrics_md = "## Performance Summary\n\n| Metric | Value | Interpretation |\n|--------|-------|----------------|\n"
        labels = {
            "oos_sharpe": ("Risk-Adjusted Return", lambda v: "Strong" if v > 1 else "Moderate" if v > 0.5 else "Weak"),
            "t_stat": ("Statistical Significance", lambda v: "Significant" if v > 2 else "Borderline" if v > 1.5 else "Not significant"),
            "max_drawdown": ("Worst Loss", lambda v: "Acceptable" if v > -0.1 else "Concerning" if v > -0.2 else "High risk"),
            "information_ratio": ("Alpha Quality", lambda v: "Good" if v > 0.5 else "Marginal"),
        }
        for k, v in spec.metrics.items():
            name, interpret = labels.get(k, (k, lambda x: ""))
            metrics_md += f"| {name} | {v} | {interpret(v)} |\n"
        cells.append(new_markdown_cell(metrics_md))

    # Figures
    if spec.figure_paths:
        cells.append(new_markdown_cell("## Visual Results"))
        for fp in spec.figure_paths:
            cells.append(_hidden_code_cell(
                f"from IPython.display import Image, display\n"
                f'display(Image(filename="{fp}", width=700))'
            ))

    # Disclaimer
    cells.append(new_markdown_cell(
        "---\n*This analysis was generated by AgentDS. "
        "Full methodology and code available in the experiment folder.*"
    ))

    nb.cells = cells
    nb.metadata.kernelspec = {"display_name": "Python 3", "language": "python", "name": "python3"}
    return nb


def save_notebook(nb: nbformat.NotebookNode, path: str) -> None:
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as f:
        nbformat.write(nb, f)


if __name__ == "__main__":
    spec = StakeholderSpec(
        title="Credit Spread Momentum Strategy",
        executive_summary="We found evidence that momentum in IG spreads predicts short-term returns in calm markets.",
        hypothesis_id="HYP-001",
        data_source="../../data/ig_spreads_clean.parquet",
        key_findings=[
            "Spread momentum generates positive risk-adjusted returns (Sharpe 0.82).",
            "Signal breaks down during high-volatility regimes.",
            "Transaction costs reduce but do not eliminate the effect.",
        ],
        metrics={"oos_sharpe": 0.82, "t_stat": 1.91, "max_drawdown": -0.043, "information_ratio": 0.61},
    )
    nb = generate_stakeholder_notebook(spec)
    save_notebook(nb, "../../notebooks/hyp_001_stakeholder.ipynb")
    print("Stakeholder notebook generated.")
